### ISSUE TITLE
Lots of error msg

### ISSUE THREAD

**Issue by Vulpecula-nl** [eandersons/energi-docker-compose#24]
Getting lots of error msg since the new update of v3.1.1

ERROR[12-28|08:40:18.103] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=5275 err="failed to initialize libusb: libusb: unknown error [code -99]"

Any idea how to fix this?

**Comment by eandersons** [comment]
I am already working on this and I have found a solution. Soon changes will be available in the repository.

**Comment by Vulpecula-nl** [comment]
Thanks for the quick response

**Comment by Vulpecula-nl** [comment]
Got one more message in the monitor container. Can you check this too?

Warning: Permanently added '[core]:2222' (RSA) to the list of known hosts.
nrgstaker@core: Permission denied (publickey)

**Comment by eandersons** [comment]
Did you run `./e3dc update` (or `git pull` followed by `docker-compose up --build --detach [core]`)? It will pull changes from the repository, rebuild images (if necessary) and recreate containers (if necessary). It is possible that some manual actions may be needed and those are described in messages for commits that were made this month.

If you still encounter the error "nrgstaker@core: Permission denied (publickey)", then it would be better to create a new issue as it is not related to the "Failed to enumerate USB devices" error.

**Comment by Vulpecula-nl** [comment]
I used the `./e3dc update` method to update. But could it be that my core container is not named `core` but `energi_core_1`?

**Comment by eandersons** [comment]
Container name is right. In Docker network each container is accessible with the alias that is the same as the name of service defined in `docker-compose.yml` (and `docker-compose.override.yml`) - `core` and `monitor` respectively.

I have rebuilt images and recreated containers multiple times since changes that introduced SSH and I have not observed the error "Permission denied (publickey)".\
This one could be hard to debug. I have a couple of things in my mind that can be checked.

Is core node container running normally and without errors in container logs?

You can try to attach to the monitor container (`docker-compose exec monitor bash`) and check if the directory `~/.ssh` exists and it contains files `id_rsa`, `id_rsa.pub` and `config`.  I suspect that those files will be there (at least `config`). If those files exist, then you can try `ssh -vT core`, and output may give some clues.

Another thing to check is if output of `docker-compose exec core ash -c 'cat ~/.sshd/authorized_keys'` is the same as of `docker-compose exec monitor bash -c 'cat ~/.ssh/id_rsa.pub'`.

If some files are missing or output of the last two commands differs, then the following commands should fix the issue: `docker-compose build`, then `docker-compose up --detach --force-recreate`.
